/* FILE NAME: readwyo.c. 
________________________________________________________________________
   2017 U.S. Government

   Licensed under the U.S. Army Research Laboratory CC0 1.0 Universal (CC0_1.0) Public Domain Dedication 
   and the Contributor License Agreement (CLA) (together known as the "License"); you may not use this 
   file except in compliance with the License.  You may obtain a copy of the License at 

       https://github.com/USArmyResearchLab.

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License. 
_________________________________________________________________________

Reads sounding data in U of Wyoming tabular format. This program produces input for the convertdatawyo and convertdatawrf programs that produce level and layer profiles in various tabular formats. These WMO soundings have heights relative to MSL. This function reads in one file in the RAOB output format as generated by the Univeristy of Wyoming.  It can read in any number of met data lines. However, for processing into an output sounding at least two lines are needed, one of which normally is the surface. The upper limit is the size of the arrays as defined in the appropriate structure definition. 
*/

#include "convert.h"

int readraob(struct sound *raob, char *inputfilename)
 {

   FILE *fin;
   char label[81];      
   char site_id[6], site[6][15], sitename[121];
   float hgt_dif;
   int i, j, ind; 
   float temp[4];
   float dummy;

/* Open input data file.  ******/

    if(!(fin = fopen(inputfilename,"r")))
     {  
        fprintf(stderr,"\nUnable to open raob input data file.\n\n");
        exit(1);
     }

/* Read input data.  *************/

 /* Set header values for ceiling and visibility equal to ERROR (-999) to avoid confusion with 
    possible real values (vs. 0.0 for each), since raob data do not include these variables. ****/

     raob->site.ceil = ERROR;
     raob->site.vis = ERROR;

 /* Read in header information. ******************************/

       fscanf(fin,"%s", site_id);
       strcpy(sitename, site_id); 
       
       fscanf(fin, "%s", site[0]);
       strcat(sitename, " ");
       strcat(sitename, site[0]);

       /*printf("sitename0: %s\n", sitename);*/
        
       i=0;
       do
         {           
           i++;
           fscanf(fin, "%s", site[i]);
           strcat(sitename, " ");
           strcat(sitename, site[i]);
         }
       while(strcmp(site[i],"Observations") != 0);

       printf("\nsitename: %s\n", sitename);
   
       fscanf(fin,"%s", label);

       fscanf(fin, "%s", raob->site.time);

       fscanf(fin, "%s", raob->site.date);
       fscanf(fin, "%s", label);
       strcat(raob->site.date, label);
       fscanf(fin, "%s", label);
       strcat(raob->site.date, label);
       printf("\ntime %s  date %s\n", raob->site.time, raob->site.date);
   
       strcpy(raob->site.time_id,"GMT");  /* set the time_id for format reasons */

       fscanf(fin,"%s", label);
       
       i=0;
       while(strcmp(label, "K") != 0)      
         {
           i++;
           fscanf(fin,"%s", label);
         }
       for(i=0;i<3;i++)
         {
           fscanf(fin,"%s", label);
         }


   /*** End of optional header reading. Common format of data follows. *********/
   /*** Read data lines.  Also checks for various situations of missing data. ******/ 

   for(j=0; j<3; j++)   /* Missing data "below surface"; i.e. the surface is above lowest standard level(s).*/
     {
        fscanf(fin,"%f", &temp[j]);
        /*printf("ind, j, temp[j] = %5d, %5d, %10.2f\n", ind, j, temp[j]);*/
     }

   while(temp[2] > 299.99)
     {
     
       temp[0] = temp[2];

       for(j=1; j<3; j++)
         {
           fscanf(fin,"%f", &temp[j]);
         }         

      }

   raob->level[0].prs = temp[0];
   raob->level[0].hgt = temp[1];
   raob->level[0].tmp = temp[2];

   fscanf(fin, "%f%f%s%f%f%f%f%f", &raob->level[0].dew, &raob->level[0].hum, label, &raob->level[0].dir, &raob->level[0].spd, &dummy, &dummy, &dummy);

   i=1;  /* Long while statement also checks for various missing data situations at upper part of sounding.*/

   while(fscanf(fin,"%f%f%f%f%f%s%f%f%f%f%f", &raob->level[i].prs, &raob->level[i].hgt, &raob->level[i].tmp, &raob->level[i].dew, 
   &raob->level[i].hum, label, &raob->level[i].dir, &raob->level[i].spd, &dummy, &dummy, &dummy) == 11 && (raob->level[i].spd < MAXWINDSPD && raob->level[i].hgt > raob->level[i-1].hgt && dummy != ERROR))     
    {     
       i++; 
    }
   printf("\n");

   raob->nht = i;

   /*printf("\nraob->nht = %5d\n\n", raob->nht);*/

  /*checkdata(raob);*/       

 /* Convert MSL heights to AGL. ****************************/

      if(raob->level[0].hgt > 0)                   /* Always true so far for U of Wyoming listings. */
         {                                         /* But just in case ... ***/
            raob->site.elev = raob->level[0].hgt;
            strcpy(raob->site.hgt_id, "MSL");
          }                                   /* Though very unlikely, the surface height could be 0. */
      else                                    /* AGL and MSL would be the same, but no effect on calculations. */ 
         strcpy(raob->site.hgt_id, "AGL");
          
     if(strcmp(raob->site.hgt_id, "MSL") == 0)     /* Change MSL to AGL.  Not used for AGL.  *****/
       { 
         if(raob->level[0].hgt < raob->site.elev) 
            raob->site.elev = raob->level[0].hgt; /* Check for raob surface vs. elevation values. */
                                                  /* Should not be necessary, but could happen.   */
         if(raob->level[0].hgt > raob->site.elev)
           hgt_dif = raob->level[0].hgt - raob->site.elev;
         else
           hgt_dif = 0; 
    
         for(i=0;i<raob->nht;i++)                  /* This loop for MSL heights only.  */
           {
             raob->level[i].hgt-= (raob->site.elev + hgt_dif);
           }
        }

 /* Convert temperature from C to K.  *****************************/

   for (i=0;i<raob->nht;i++)
     {
        raob->level[i].tmp += 273.16;  
     }


 /* Get latitude, longitude, and elevation from information section that follows data columns. */

   while(strcmp(label, "latitude:") != 0)
      fscanf(fin, "%s", label);
   fscanf(fin,"%f", &raob->site.lat);

   while(strcmp(label, "longitude:") != 0)
      fscanf(fin, "%s", label);
   fscanf(fin,"%f", &raob->site.lon);

   while(strcmp(label, "elevation:") != 0)
      fscanf(fin, "%s", label);
   fscanf(fin,"%f", &raob->site.elev);

   printf("\n");

/***********************************************/

  fclose(fin);
  
  return;
}


     
